package excecoes;

public class Teste {
	public static void main(String[] args) {
		
		try {
			
		} catch (ArithmeticException ex) {
			// TODO: handle exception
		}
		catch (Exception ex) {
			
		}
		
	}

}
